services:
  db:
    image: postgres:15-alpine
    container_name: publicidade_db
    restart: always
    environment:
      POSTGRES_DB: publicidade_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: