version: '3.8'

services:
  backend:
    image: nginx:stable-alpine
    container_name: publicidade_backend_server
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  php:
    build:
      context: ./docker/php
    container_name: publicidade_php_fpm
    volumes:
      - ./backend:/var/www/html

  db:
    image: postgres:15-alpine
    container_name: publicidade_db
    restart: always
    environment:
      POSTGRES_DB: publicidade_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    image: node:20-alpine
    container_name: publicidade_frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm start

  composer:
    image: composer:latest
    container_name: publicidade_composer
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html

volumes:
  pgdata: